name: Build chiaki-borealis

on:
  push:
  pull_request:

jobs:
  msys2-w64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake python3-pip mingw-w64-x86_64-7zip mingw-w64-x86_64-SDL2 make ninja yasm pkg-config diffutils mingw-w64-x86_64-glm mingw-w64-x86_64-glfw mingw-w64-x86_64-libiconv
      - name: msys2-build-chiaki
        run: |
          ls -alh /c/hostedtoolcache/windows/Python/3.9.13/x64
          ./scripts/github-msys2-build.sh
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-borealis
          path: |
            ChiakiBorealis
  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: scripts/flatpak/com.github.thestr4ng3r.Chiaki.json